name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON files
        run: |
          python -mjson.tool 'he.json' > /dev/null
          python -mjson.tool 'module.json' > /dev/null
